FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
ARG PROJECT
WORKDIR /src
COPY . .
RUN dotnet publish ${PROJECT}/${PROJECT}.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview
ARG PROJECT
ENV DOTNET_DLL="${PROJECT}.dll"
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT dotnet $DOTNET_DLL
